"""create room

Revision ID: 1d4ae8af2d7c
Revises: 917d6dcf38a0
Create Date: 2026-03-05 23:17:38.635439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4ae8af2d7c'
down_revision: Union[str, Sequence[str], None] = '917d6dcf38a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('IN_GAME', 'PAUSED', name='roomstatus'), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_owner_id'), 'rooms', ['owner_id'], unique=False)
    op.create_table('room_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('room_role', sa.Enum('DM', 'PLAYER', 'SPECTATOR', name='roomrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creature_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('max_hp', sa.Integer(), nullable=True),
    sa.Column('ac', sa.Integer(), nullable=True),
    sa.Column('cr', sa.Integer(), nullable=False),
    sa.Column('size', sa.Enum('TINY', 'SMALL', 'MEDIUM', 'LARGE', 'HUGE', 'GARGANTUAN', 'COLOSSAL', name='creaturesize'), nullable=False),
    sa.Column('type', sa.Enum('PLANTS', 'BEASTS', 'HUMANOIDS', 'GIANTS', 'FEY', 'OOZES', 'CONSTRUCTS', 'ABERRATIONS', 'UNDEAD', 'DRAGONS', 'CELESTIALS', 'FIENDS', 'ELEMENTALS', 'MONSTROSITIES', name='creaturetype'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_creature_cr', 'creature_templates', ['cr'], unique=False)
    op.create_index('idx_creature_size', 'creature_templates', ['size'], unique=False)
    op.create_index('idx_creature_type', 'creature_templates', ['type'], unique=False)
    op.create_table('map_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_maps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('name_in_room', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['map_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('creature_template_id', sa.Integer(), nullable=True),
    sa.Column('name_in_room', sa.String(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('rotation', sa.Float(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('controlled_by', sa.UUID(), nullable=True),
    sa.Column('current_hp', sa.Integer(), nullable=True),
    sa.Column('current_ac', sa.Integer(), nullable=True),
    sa.Column('conditions', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['controlled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creature_template_id'], ['creature_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_room_tokens_position', 'room_tokens', ['room_id', 'position_x', 'position_y'], unique=False)
    op.create_index('idx_room_tokens_room', 'room_tokens', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_room_tokens_room', table_name='room_tokens')
    op.drop_index('idx_room_tokens_position', table_name='room_tokens')
    op.drop_table('room_tokens')
    op.drop_table('room_maps')
    op.drop_table('map_templates')
    op.drop_index('idx_creature_type', table_name='creature_templates')
    op.drop_index('idx_creature_size', table_name='creature_templates')
    op.drop_index('idx_creature_cr', table_name='creature_templates')
    op.drop_table('creature_templates')
    op.drop_table('room_users')
    op.drop_index(op.f('ix_rooms_owner_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
