"""Add active_map_id to rooms

Revision ID: 2d6b2c85141f
Revises: b4f9d7fd1614
Create Date: 2026-03-27 14:17:40.889863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6b2c85141f'
down_revision: Union[str, Sequence[str], None] = 'b4f9d7fd1614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('active_map_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rooms', 'room_maps', ['active_map_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'active_map_id')
    # ### end Alembic commands ###
