"""add image_id to room_maps

Revision ID: 411c21bf4892
Revises: 2d6b2c85141f
Create Date: 2026-03-27 19:08:11.414537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411c21bf4892'
down_revision: Union[str, Sequence[str], None] = '2d6b2c85141f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_maps', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'room_maps', 'images', ['image_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('rooms_active_map_id_fkey'), 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'active_map_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('active_map_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('rooms_active_map_id_fkey'), 'rooms', 'room_maps', ['active_map_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'room_maps', type_='foreignkey')
    op.drop_column('room_maps', 'image_id')
    # ### end Alembic commands ###
