"""remove_duplicate_hp_ac_from_templates

Revision ID: 42ca38bb42f5
Revises: b1709777fb66
Create Date: 2026-04-17 20:46:50.543967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ca38bb42f5'
down_revision: Union[str, Sequence[str], None] = 'b1709777fb66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creature_templates', sa.Column('max_hp', sa.Integer(), nullable=True))
    op.add_column('creature_templates', sa.Column('ac', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creature_templates', 'ac')
    op.drop_column('creature_templates', 'max_hp')
    # ### end Alembic commands ###
