"""add relationship image in roomtoken

Revision ID: 457d76f19988
Revises: d6f00a2ce477
Create Date: 2026-04-16 20:30:07.020548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '457d76f19988'
down_revision: Union[str, Sequence[str], None] = 'd6f00a2ce477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_tokens', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'room_tokens', 'images', ['image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_tokens', type_='foreignkey')
    op.drop_column('room_tokens', 'image_id')
    # ### end Alembic commands ###
