"""add map editor tables

Revision ID: 6126b3a6dd55
Revises: c0d278ba8263
Create Date: 2026-04-29 12:50:28.621091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6126b3a6dd55'
down_revision: Union[str, Sequence[str], None] = 'c0d278ba8263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_packs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asset_packs_is_public', 'asset_packs', ['is_public'], unique=False)
    op.create_index('idx_asset_packs_owner_id', 'asset_packs', ['owner_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('default_width', sa.Integer(), nullable=False),
    sa.Column('default_height', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_rotatable', sa.Boolean(), nullable=True),
    sa.Column('snap_to_grid', sa.Boolean(), nullable=True),
    sa.Column('grid_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pack_id'], ['asset_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assets_category', 'assets', ['category'], unique=False)
    op.create_index('idx_assets_pack_id', 'assets', ['pack_id'], unique=False)
    op.create_table('map_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('orientation', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('grid_size', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('pack_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pack_id'], ['asset_packs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['map_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_map_projects_owner_id', 'map_projects', ['owner_id'], unique=False)
    op.create_index('idx_map_projects_template_id', 'map_projects', ['template_id'], unique=False)
    op.create_index('idx_map_projects_updated_at', 'map_projects', ['updated_at'], unique=False)
    op.create_table('background_layers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('grid_data', sa.JSON(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['map_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index('idx_background_layers_project_id', 'background_layers', ['project_id'], unique=False)
    op.create_table('scene_objects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('rotation', sa.Float(), nullable=True),
    sa.Column('z_index', sa.Integer(), nullable=True),
    sa.Column('tint_color', sa.String(), nullable=True),
    sa.Column('opacity', sa.Float(), nullable=True),
    sa.Column('flipped_h', sa.Boolean(), nullable=True),
    sa.Column('flipped_v', sa.Boolean(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['map_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scene_objects_asset_id', 'scene_objects', ['asset_id'], unique=False)
    op.create_index('idx_scene_objects_project_id', 'scene_objects', ['project_id'], unique=False)
    op.create_index('idx_scene_objects_z_index', 'scene_objects', ['z_index'], unique=False)
    op.drop_index(op.f('idx_templates_public_rank'), table_name='map_templates', postgresql_where='(is_public = true)')
    op.create_index('idx_templates_public_rank', 'map_templates', ['is_public', 'rating', 'votes'], unique=False, postgresql_where='is_public = true', postgresql_ops={'rating': 'DESC', 'votes': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_templates_public_rank', table_name='map_templates', postgresql_where='is_public = true', postgresql_ops={'rating': 'DESC', 'votes': 'DESC'})
    op.create_index(op.f('idx_templates_public_rank'), 'map_templates', ['is_public', sa.literal_column('rating DESC'), sa.literal_column('votes DESC')], unique=False, postgresql_where='(is_public = true)')
    op.drop_index('idx_scene_objects_z_index', table_name='scene_objects')
    op.drop_index('idx_scene_objects_project_id', table_name='scene_objects')
    op.drop_index('idx_scene_objects_asset_id', table_name='scene_objects')
    op.drop_table('scene_objects')
    op.drop_index('idx_background_layers_project_id', table_name='background_layers')
    op.drop_table('background_layers')
    op.drop_index('idx_map_projects_updated_at', table_name='map_projects')
    op.drop_index('idx_map_projects_template_id', table_name='map_projects')
    op.drop_index('idx_map_projects_owner_id', table_name='map_projects')
    op.drop_table('map_projects')
    op.drop_index('idx_assets_pack_id', table_name='assets')
    op.drop_index('idx_assets_category', table_name='assets')
    op.drop_table('assets')
    op.drop_index('idx_asset_packs_owner_id', table_name='asset_packs')
    op.drop_index('idx_asset_packs_is_public', table_name='asset_packs')
    op.drop_table('asset_packs')
    # ### end Alembic commands ###
