"""add_owner_and_rating_to_map_templates

Revision ID: 65147c302894
Revises: 261eac548e44
Create Date: 2026-04-25 14:48:06.205146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65147c302894'
down_revision: Union[str, Sequence[str], None] = '261eac548e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('map_template_tags',
    sa.Column('map_template_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['map_template_id'], ['map_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('map_template_id', 'tag_id')
    )
    op.create_index('idx_map_template_tags_tag_id', 'map_template_tags', ['tag_id'], unique=False)
    
    op.add_column('map_templates', sa.Column('owner_id', sa.UUID(), nullable=True))
    
    op.execute("""
        UPDATE map_templates 
        SET owner_id = (SELECT id FROM users LIMIT 1)
        WHERE owner_id IS NULL;
    """)
    
    op.alter_column('map_templates', 'owner_id', existing_type=sa.UUID(), nullable=False)
    
    op.add_column('map_templates', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('map_templates', sa.Column('rating', sa.Numeric(precision=3, scale=1), server_default='0', nullable=False))
    op.add_column('map_templates', sa.Column('votes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('map_templates', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('map_templates', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('idx_map_templates_created_at', 'map_templates', ['created_at'], unique=False)
    op.create_index('idx_map_templates_is_public', 'map_templates', ['is_public'], unique=False)
    op.create_index('idx_map_templates_owner_id', 'map_templates', ['owner_id'], unique=False)
    op.create_index('idx_templates_public_rank', 'map_templates', ['is_public', 'rating', 'votes'], unique=False, postgresql_where='is_public = true', postgresql_ops={'rating': 'DESC', 'votes': 'DESC'})
    op.create_foreign_key(None, 'map_templates', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'map_templates', type_='foreignkey')
    op.drop_index('idx_templates_public_rank', table_name='map_templates', postgresql_where='is_public = true', postgresql_ops={'rating': 'DESC', 'votes': 'DESC'})
    op.drop_index('idx_map_templates_owner_id', table_name='map_templates')
    op.drop_index('idx_map_templates_is_public', table_name='map_templates')
    op.drop_index('idx_map_templates_created_at', table_name='map_templates')
    op.drop_column('map_templates', 'updated_at')
    op.drop_column('map_templates', 'created_at')
    op.drop_column('map_templates', 'votes')
    op.drop_column('map_templates', 'rating')
    op.drop_column('map_templates', 'is_public')
    op.drop_column('map_templates', 'owner_id')
    op.drop_index('idx_map_template_tags_tag_id', table_name='map_template_tags')
    op.drop_table('map_template_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
