"""add_users_relationship

Revision ID: 6f42ce474046
Revises: 65147c302894
Create Date: 2026-04-25 15:03:18.567604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f42ce474046'
down_revision: Union[str, Sequence[str], None] = '65147c302894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('map_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('map_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_templates_public_rank'), table_name='map_templates', postgresql_where='(is_public = true)')
    op.create_index('idx_templates_public_rank', 'map_templates', ['is_public', 'rating', 'votes'], unique=False, postgresql_where='is_public = true', postgresql_ops={'rating': 'DESC', 'votes': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_templates_public_rank', table_name='map_templates', postgresql_where='is_public = true', postgresql_ops={'rating': 'DESC', 'votes': 'DESC'})
    op.create_index(op.f('idx_templates_public_rank'), 'map_templates', ['is_public', sa.literal_column('rating DESC'), sa.literal_column('votes DESC')], unique=False, postgresql_where='(is_public = true)')
    op.alter_column('map_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('map_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
