"""add created_at and updated_at to room_tokens

Revision ID: 70af3c69d480
Revises: ed51267cf7c2
Create Date: 2026-03-14 16:00:32.402986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70af3c69d480'
down_revision: Union[str, Sequence[str], None] = 'ed51267cf7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_tokens', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('room_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_tokens', 'updated_at')
    op.drop_column('room_tokens', 'created_at')
    # ### end Alembic commands ###
