"""Add creature_details and child tables

Revision ID: 75cc6da4d5da
Revises: 457d76f19988
Create Date: 2026-04-17 18:03:36.840973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75cc6da4d5da'
down_revision: Union[str, Sequence[str], None] = '457d76f19988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creature_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('dexterity', sa.Integer(), nullable=True),
    sa.Column('constitution', sa.Integer(), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('wisdom', sa.Integer(), nullable=True),
    sa.Column('charisma', sa.Integer(), nullable=True),
    sa.Column('hp_max', sa.Integer(), nullable=True),
    sa.Column('hit_dice', sa.String(), nullable=True),
    sa.Column('ac', sa.Integer(), nullable=True),
    sa.Column('speed', sa.String(), nullable=True),
    sa.Column('languages', sa.String(), nullable=True),
    sa.Column('cr', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['creature_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id')
    )
    op.create_table('creature_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('details_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['details_id'], ['creature_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creature_attacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('details_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('to_hit', sa.Integer(), nullable=True),
    sa.Column('damage', sa.String(), nullable=True),
    sa.Column('damage_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['details_id'], ['creature_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creature_legendary_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('details_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['details_id'], ['creature_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creature_reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('details_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['details_id'], ['creature_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creature_resistances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('details_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['details_id'], ['creature_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creature_saves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('details_id', sa.Integer(), nullable=False),
    sa.Column('ability', sa.String(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['details_id'], ['creature_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creature_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('details_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['details_id'], ['creature_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creature_traits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('details_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['details_id'], ['creature_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('room_tokens_image_id_fkey'), 'room_tokens', type_='foreignkey')
    op.drop_column('room_tokens', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_tokens', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('room_tokens_image_id_fkey'), 'room_tokens', 'images', ['image_id'], ['id'], ondelete='SET NULL')
    op.drop_table('creature_traits')
    op.drop_table('creature_skills')
    op.drop_table('creature_saves')
    op.drop_table('creature_resistances')
    op.drop_table('creature_reactions')
    op.drop_table('creature_legendary_actions')
    op.drop_table('creature_attacks')
    op.drop_table('creature_actions')
    op.drop_table('creature_details')
    # ### end Alembic commands ###
