"""Add RoomSettings and RoomPage tables

Revision ID: 806e61e844db
Revises: 411c21bf4892
Create Date: 2026-03-31 15:03:16.955920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '806e61e844db'
down_revision: Union[str, Sequence[str], None] = '411c21bf4892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('background_color', sa.String(), nullable=True),
    sa.Column('grid_size', sa.Integer(), nullable=True),
    sa.Column('grid_visible', sa.Boolean(), nullable=True),
    sa.Column('players_can_draw', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['room_maps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('grid_size', sa.Integer(), nullable=True),
    sa.Column('players_can_draw', sa.Boolean(), nullable=True),
    sa.Column('music_volume', sa.Integer(), nullable=True),
    sa.Column('require_password', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id')
    )
    op.add_column('room_tokens', sa.Column('page_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'room_tokens', 'room_pages', ['page_id'], ['id'], ondelete='CASCADE')
    op.add_column('rooms', sa.Column('active_page_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rooms', 'room_pages', ['active_page_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'active_page_id')
    op.drop_constraint(None, 'room_tokens', type_='foreignkey')
    op.drop_column('room_tokens', 'page_id')
    op.drop_table('room_settings')
    op.drop_table('room_pages')
    # ### end Alembic commands ###
