"""create media tables

Revision ID: 917d6dcf38a0
Revises: 
Create Date: 2026-03-05 21:50:02.686814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917d6dcf38a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('storage_provider', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('MEDIA_FILE', 'IMAGE', 'AUDIO', name='mediatype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('idx_media_files_created_at', 'media_files', ['created_at'], unique=False)
    op.create_index('idx_media_files_deleted_at', 'media_files', ['deleted_at'], unique=False)
    op.create_index('idx_media_files_media_type', 'media_files', ['media_type'], unique=False)
    op.create_index('idx_media_files_uploaded_by', 'media_files', ['uploaded_by'], unique=False)
    op.create_table('audio_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('album', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('audio_codec', sa.String(), nullable=True),
    sa.Column('waveform_data', sa.JSON(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('palette', sa.JSON(), nullable=True),
    sa.Column('is_dark', sa.Boolean(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('thumbnail_id', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('blurhash', sa.String(), nullable=True),
    sa.Column('has_alpha', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thumbnail_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('audio_files')
    op.drop_index('idx_media_files_uploaded_by', table_name='media_files')
    op.drop_index('idx_media_files_media_type', table_name='media_files')
    op.drop_index('idx_media_files_deleted_at', table_name='media_files')
    op.drop_index('idx_media_files_created_at', table_name='media_files')
    op.drop_table('media_files')
    # ### end Alembic commands ###
