"""remove_duplicate_hp_ac_from_templates

Revision ID: ae13963f061b
Revises: 42ca38bb42f5
Create Date: 2026-04-17 21:40:47.969921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae13963f061b'
down_revision: Union[str, Sequence[str], None] = '42ca38bb42f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creature_templates', 'max_hp')
    op.drop_column('creature_templates', 'ac')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creature_templates', sa.Column('ac', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('creature_templates', sa.Column('max_hp', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
