"""Add image_id to rooms

Revision ID: b4f9d7fd1614
Revises: 70af3c69d480
Create Date: 2026-03-24 17:53:27.937483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f9d7fd1614'
down_revision: Union[str, Sequence[str], None] = '70af3c69d480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('image_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key(None, 'rooms', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'image_id')
    # ### end Alembic commands ###
