"""add audio tables

Revision ID: b61b0b6bf87f
Revises: 6126b3a6dd55
Create Date: 2026-05-03 14:38:08.260392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b61b0b6bf87f'
down_revision: Union[str, Sequence[str], None] = '6126b3a6dd55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('cover_image_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cover_image_id'], ['images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_audio_tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('audio_file_id', sa.Integer(), nullable=False),
    sa.Column('name_in_room', sa.String(), nullable=True),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('audio_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('custom_title', sa.String(), nullable=True),
    sa.Column('custom_artist', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['audio_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_id', 'audio_id', name='uq_playlist_audio'),
    sa.UniqueConstraint('playlist_id', 'position', name='uq_playlist_position')
    )
    op.create_table('room_audio_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('current_playlist_id', sa.Integer(), nullable=True),
    sa.Column('current_track_id', sa.Integer(), nullable=True),
    sa.Column('track_position_ms', sa.Integer(), nullable=True),
    sa.Column('playlist_index', sa.Integer(), nullable=True),
    sa.Column('is_playing', sa.Boolean(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('repeat_mode', sa.Enum('NONE', 'ONE', 'ALL', name='repeatmode'), nullable=True),
    sa.Column('shuffle', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_playlist_id'], ['playlists.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_track_id'], ['audio_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id')
    )
    op.drop_column('assets', 'grid_size')
    op.drop_column('map_projects', 'grid_size')
    op.drop_index(op.f('idx_templates_public_rank'), table_name='map_templates', postgresql_where='(is_public = true)')
    op.create_index('idx_templates_public_rank', 'map_templates', ['is_public', 'rating', 'votes'], unique=False, postgresql_where='is_public = true', postgresql_ops={'rating': 'DESC', 'votes': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_templates_public_rank', table_name='map_templates', postgresql_where='is_public = true', postgresql_ops={'rating': 'DESC', 'votes': 'DESC'})
    op.create_index(op.f('idx_templates_public_rank'), 'map_templates', ['is_public', sa.literal_column('rating DESC'), sa.literal_column('votes DESC')], unique=False, postgresql_where='(is_public = true)')
    op.add_column('map_projects', sa.Column('grid_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('grid_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('room_audio_players')
    op.drop_table('playlist_tracks')
    op.drop_table('room_audio_tracks')
    op.drop_table('playlists')
    # ### end Alembic commands ###
