"""add map editor tables

Revision ID: c0d278ba8263
Revises: 6f42ce474046
Create Date: 2026-04-29 12:37:54.780473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d278ba8263'
down_revision: Union[str, Sequence[str], None] = '6f42ce474046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_templates_public_rank'), table_name='map_templates', postgresql_where='(is_public = true)')
    op.create_index('idx_templates_public_rank', 'map_templates', ['is_public', 'rating', 'votes'], unique=False, postgresql_where='is_public = true', postgresql_ops={'rating': 'DESC', 'votes': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_templates_public_rank', table_name='map_templates', postgresql_where='is_public = true', postgresql_ops={'rating': 'DESC', 'votes': 'DESC'})
    op.create_index(op.f('idx_templates_public_rank'), 'map_templates', ['is_public', sa.literal_column('rating DESC'), sa.literal_column('votes DESC')], unique=False, postgresql_where='(is_public = true)')
    # ### end Alembic commands ###
