"""add page_id to room_tokens

Revision ID: d6f00a2ce477
Revises: fadb2b4cb4b4
Create Date: 2026-04-11 00:15:44.661961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6f00a2ce477'
down_revision: Union[str, Sequence[str], None] = 'fadb2b4cb4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room_tokens', 'page_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('room_tokens_image_id_fkey'), 'room_tokens', type_='foreignkey')
    op.drop_column('room_tokens', 'token_type')
    op.drop_column('room_tokens', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_tokens', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('room_tokens', sa.Column('token_type', postgresql.ENUM('creature', 'prop', name='tokentype'), server_default=sa.text("'creature'::tokentype"), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('room_tokens_image_id_fkey'), 'room_tokens', 'images', ['image_id'], ['id'], ondelete='SET NULL')
    op.alter_column('room_tokens', 'page_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
