"""add created_at to room_maps

Revision ID: ed51267cf7c2
Revises: 1d4ae8af2d7c
Create Date: 2026-03-12 16:56:07.358538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed51267cf7c2'
down_revision: Union[str, Sequence[str], None] = '1d4ae8af2d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_maps', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('room_maps', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_maps', 'updated_at')
    op.drop_column('room_maps', 'created_at')
    # ### end Alembic commands ###
