"""add settings models for rooms

Revision ID: ee87a81a1d47
Revises: 806e61e844db
Create Date: 2026-04-05 11:53:30.380852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee87a81a1d47'
down_revision: Union[str, Sequence[str], None] = '806e61e844db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('current_page_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('rooms_active_page_id_fkey'), 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'room_pages', ['current_page_id'], ['id'], ondelete='SET NULL')
    op.drop_column('rooms', 'active_page_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('active_page_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('rooms_active_page_id_fkey'), 'rooms', 'room_pages', ['active_page_id'], ['id'], ondelete='SET NULL')
    op.drop_column('rooms', 'current_page_id')
    # ### end Alembic commands ###
