port: 7880
rtc:
  tcp_port: 7881
  udp_port: 7882
  use_external_ip: false
  node_ip: 192.168.0.109
keys:
  APILocalKey123: fbcba4553a2931d791341fd0f0ed0555
logging:
  level: info
room:
  enabled_codecs:
    - mime: video/vp8
    - mime: video/vp9
    - mime: video/h264
    - mime: audio/opus
